Add showpenalty option
zakkak/turnin pull request #54
Opened 2024-10-17 15:02 UTC by PaulWalther

2024-10-17 15:12 UTC, zakkak requested changes
Hi @PaulWalther, thank you for your contribution.

It LGTM, could you just address the suggested styling issues before I can merge this? Thank you.

2024-10-17 15:12 UTC, zakkak commented on src/turnin.c
> +			"Copyright 2024 	 Paul Walther     <paul.walther@tum.de>\n\n"
```suggestion
	        "Copyright 2015-2022 Foivos S. Zakkak <foivos@zakkak.net>\n"
	        "Copyright 2024      Paul Walther     <paul.walther@tum.de>\n\n"
```

2024-10-17 15:12 UTC, zakkak commented on src/turnin.c
> +			else if (strcasecmp(keyword, "duedate") == 0) {
```suggestion
			} else if (strcasecmp(keyword, "duedate") == 0) {
```

2024-10-17 15:12 UTC, zakkak commented on src/turnin.c
> +	if ((penalty > 0)&& (showpenalty)) {
```suggestion
	if ((penalty > 0) && showpenalty) {
```

2024-10-18 08:52 UTC, PaulWalther commented
Hey @zakkak . Sure, should have looked into the styleguide before opening the PR. I applied your changes. Best regards

2024-10-18 09:02 UTC, merged